<div class="header-container">
    <div class="header">
        <h1 class="logo"><strong><?php echo $this->getLogoAlt() ?></strong><a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><img width="160" src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a></h1>
        <div class="quick-access">
            <div class="header-middle">
                <?php echo $this->getChildHtml('topSearch') ?>
            </div>
            <div class="header-right">
                <?php echo $this->getChildHtml('topLinks') ?>
                <?php echo $this->getChildHtml('store_language') ?>
            </div>
        </div>
        <?php echo $this->getChildHtml('topContainer'); ?>
    </div>
</div>
<div class="menu-slider-wrapper">
    <?php echo $this->getChildHtml('topMenu') ?>
    <?php
    echo $this->getLayout()->createBlock('bannerslider/default')
            ->setTemplate('bannerslider/bannerslider.phtml')
            ->setBannersliderId(1)->toHtml();
    ?>
</div>
